### ISSUE TITLE
As a developer I need type safety in meta data from paginated responses

### ISSUE THREAD

**Issue by IgorJoergensen** [OmniCar/SAM-types#39]
As a developer I need type safety in the returned metadata given in a paginated response

To see a use case task for this - look at: https://github.com/OmniCar/SAM-api/issues/1736

The interface ```IPaginatedResult``` should be extended with these keys and types in the file searchQuery.d.ts

```
{
  orderBy: string
  orderDirection: 'ASC' | 'DESC'
}
```

**Comment by olefrank** [comment]
solved in v0.0.30
